### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by kinto-b** [kinto-b/makepipe#10]
First release:
* [x] #11
* [x] `usethis::use_cran_comments()`
* [x] Proof read `Title:` and `Description:`
* [x] Check that all exported functions have `@returns` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>
* [x] Review checklist here: https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/r-package/#section6
* [x]  #12

Prepare for release:
* [x] `devtools::build_readme()`
* [x] [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker)
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`

Submit to CRAN:
* [x] `devtools::submit_cran()`
* [x] Approve email
* [x] Action feedback:
  * [x] Add some more details about the package functionality and implemented methods in the Description text.
  * [x] Replace call to `installed.packages()` with `find.package()`
* [x] Resubmit

Wait for CRAN...
* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] Update install instructions in README
* [x] Once accepted, submit to R Weekly: https://github.com/rweekly/rweekly.org/blob/gh-pages/draft.md

**Comment by kinto-b** [comment]
Submitted! 🎉

**Comment by gorcha** [comment]
:champagne:
