### ISSUE TITLE
Add execution time to metadata

### ISSUE THREAD

**Issue by kinto-b** [kinto-b/makepipe#24]
It would be useful to keep track of how long each part of the pipeline takes to run

**Comment by kinto-b** [comment]
@gorcha got a design problem for you.

So we've got these two metadata containers: the `Pipeline` and the `makepipe_result`. The latter is produced by each `make_*()` segment. 

They perform slightly different work. The `Pipeline` tells us about the whole pipeline, and is somewhat independent of any given execution of it. The `makepipe_result` tells us about each individual segment, and is entirely dependent on the particular execution.

Execution time obviously belongs in the `makepipe_result`. I'm wondering whether it should also be kept in the `Pipeline`. 

The main reason to have it in the `Pipeline` is that it'd mean you'd only have to look in one place to get the execution time information for all the bits of the pipeline. 

What do you think

**Comment by kinto-b** [comment]
If it goes in the `Pipeline`, then there's the potential to do some kind of visualisation, e.g. `show_timeline()`, that exhibits the relative time costs of each step in the process

**Comment by gorcha** [comment]
Hey! I kind of agree with both approaches 😛 - I think the whole result object should be linked to the pipeline somehow so you can visualise results of the run (e.g. which steps were refreshed, which dependencies were out of date and triggered the refresh).

Really I think the "segment" on the pipeline should include the result as an attribute - possibly easier to implement the segment as an R6 object to take advantage of reference semantics?

So for e.g. `make_with_source()` might look something like this:
```r
make_with_source <- function(...) {

  pipeline <- get_pipeline()
  if (is.null(pipeline)) {
    pipeline <- Pipeline$new()
    set_pipeline(pipeline)
  }
  segment <- pipeline$add_source_segment( # This returns an R6 pipeline segment object
    source = source,
    targets = targets,
    dependencies = dependencies,
    packages = packages
  )

  out <- makepipe_result(
    executed = outdated,
    result = as.list(register_env),
    instructions = source,
    targets = targets,
    dependencies = dependencies,
    packages = packages,
    envir = envir,
    subclass = "source"
  )

  segment$add_result(out)

  invisible(out)
}
```

**Comment by kinto-b** [comment]
Yeah, I think this is a good idea.

Since a `Pipeline` is constructed segment-by-segment by calling `make_*()`, it makes a lot of sense for it to actually consist of `Segment` objects. And it makes sense for these to be richer than the `Pipeline` network, which mainly just exists for visualisation purposes.

I think this'll tie in nicely with #3 since it should be straightforward to implement an `Segment$execute()` method. Then all the `build()` function has to do is figure out the order of execution and then loop through the segments calling `$execute()` on each of them. 


Thanks!

**Comment by kinto-b** [comment]
Will be in next release
