### ISSUE TITLE
`make_with_recipe`: Error in basename(as.character(nodes$id)): path too long

### ISSUE THREAD

**Issue by g-hyo** [kinto-b/makepipe#37]
It looks like `make_with_recipe` runs into an error when the recipe has more than a few lines of code

``` r
library(makepipe)
#> Warning: package 'makepipe' was built under R version 4.0.5
saveRDS(cars, 'raw_dat.rds')
make_with_recipe(
  recipe = {
    new_cars <- cars
    new_cars$a <- 1
    new_cars$b <- 2
    new_cars$c <- 3
    new_cars$d <- 4
    new_cars$e <- 5
    new_cars$f <- 6
    new_cars$g <- 7
    new_cars$h <- 8
    new_cars$i <- 9
    new_cars$i <- 10
   saveRDS(new_cars, 'processed_dat.rds')
  },
  
  dependencies = 'raw_dat.rds',
  targets = 'processed_dat.rds'
  
)
#> Error in basename(as.character(nodes$id)): path too long
```

<sup>Created on 2022-05-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Seems like it may have something to do with the makepipe visualisation?

**Comment by kinto-b** [comment]
Thanks for this! I've been doing a bit of work lately getting an 0.2.0 ready. I'll make sure to fix this in time for the next release :)
