### ISSUE TITLE
Use roxygen-like tags to declare dependencies

### ISSUE THREAD

**Issue by kinto-b** [kinto-b/makepipe#41]
At the top of each script, something like

```r
#' @title Merge
#' @description Merge population variables into survey data.
#' @dependencies [ "data/2 dat.Rds", "data/0 pop.Rds"]
#' @targets "data/3 dat.Rds"
NULL
```

Then something like `make_with_dir()` to either generate an R script containing `make_with_*()` blocks or else to simply execute the pipeline

**Comment by kinto-b** [comment]
@g-hyo Reckon this would be a better way to manage a pipeline than having a separate script? Then you just hit `make_with_dir()` in the console to execute the entire pipeline

**Comment by g-hyo** [comment]
Specifying dependencies and targets at the start of the script would definitely simplify things! Seems like good practice to specify dependencies and targets within a script anyway. 

`make_with_dir()` also sounds incredibly convenient. Would it be possible to use a tag like like `@makepipe` to indicate which scripts end up part of the pipeline? Then scripts could easily be disabled without having to move them in and out of the directory

Also, I wonder if it its worth having a helper function that could be used to automatically generate/execute a `make_with_*()` code block (sort of like a replacement for `source()`)
```
makepipe("some_script.R")
```

**Comment by kinto-b** [comment]
Both such good ideas!
